### ISSUE TITLE
Rechtliches - Finanzamt / Was passiert mit Einnahmen ?

### ISSUE THREAD

**Issue by Nanabell** [Nanabell/Esoteric-Website#1]
Wir müssen klären was mit einnahmen passiert wenn wir wirklich Geld einnehmen würden.

**Comment by Macho2406** [comment]
Einkommensteuergesetz: Diese 7 Einkunftsarten sind steuerpflichtig
 
Das Einkommensteuergesetz kennt 7 sogenannte Einkunftsarten, die bei der Berechnung der Einkommensteuer berücksichtigt werden. Für Laien immer wieder überraschend ist die Tatsache, dass es durchaus zahlreiche Einnahmen gibt, auf die ein Steuerpflichtiger – trotz gewaltiger Summen – keine Einkommensteuer zahlen muss. Das bekannteste Beispiel ist der Lottogewinn: Ein Sechser im Lotto ist meist eine ordentliche Summe – und trotzdem kein Fall für das Finanzamt, da er unter keine der folgenden 7 Einkunftsarten fällt, die der Einkommensteuer unterliegen:
 
Einkommen aus nichtselbstständiger oder selbstständiger Arbeit
Einkommen aus einem Gewerbebetrieb
Einkünfte aus Kapitalvermögen (Zinsen, Dividenden, Kursgewinne bei Aktienverkäufen etc.)
Einkünfte aus Vermietung und Verpachtung
Einkommen aus gesetzlichen oder betrieblichen Renten etc.
Einkünfte aus Land- und Forstwirtschaft
Sonstige Einkünfte im Sinne des Auffangparagrafen 22 im Einkommensteuergesetz

Also müssen wir unsere Einnahmen beim Finanzamt melden und versteuern

**Comment by Dustin2112** [comment]
Update: Siehe Closed Issue "Rechtliches - Dürfen Schüler Geld verdienen?"
