### ISSUE TITLE
Impressum

### ISSUE THREAD

**Issue by Nanabell** [Nanabell/Esoteric-Website#18]
erstellen eines Impressums

**Comment by Dustin2112** [comment]
Rechtliche Hinweise: 

Wir möchten Sie darauf aufmerksam machen, dass bei den Produkten, die wir auf unserer Homepage (www.esotech.jit4u.de) und in sonstigen Produktinformationen anbieten, nach den naturwissenschaftlichen Kriterien der Schulwissenschaft keine Wirksamkeit besteht. Nach den Theorien und Standards der Schulwissenschaft ist es ausgeschlossen, dass unsere Geräte Orgonenergie sammeln und konzentrieren.

Als Käufer der Esotech Produkte erwerben Sie also Geräte, die auf Gedanken von Außenseitern beruhen. Nach den naturwissenschaftlichen Kriterien der Schulwissenschaft können die Produkte lediglich eine Placebo-Wirkung auf Gesundheit und Wohlbefinden der Anwender haben.

Bei einem Krankheitsverdacht, gesundheitlichen Beschwerden oder Erkrankungen wenden Sie sich zur Diagnose und Behandlung bitte unbedingt und unverzüglich an Ihren Arzt oder Heilpraktiker.

Die Anwendung der Esotech Produkte dient Ihrem Wohlbefinden und hat keine medizinischen Zwecke. Ihre Nutzung sollte nicht dazu führen, dass Sie eine Untersuchung oder die Betreuung durch Ihren Arzt oder Heilpraktiker hinauszögern, unterbrechen oder beenden.

Alle Angaben zu orgonspezifischen Eigenschaften der Esotech Produkte auf unserer Homepage (www.esotech.jit4u.de) und in sonstigen Produktinformationen von uns beruhen auf praktischen Erfahrungen im Umgang mit diesen Produkten. Durch technische Messgeräte sind sie so nicht festzustellen.

**Comment by Macho2406** [comment]
Datenschutz:

Ihre personenbezogenen Daten, welche erforderlich sind, um die Inanspruchnahme unserer Angebote zu ermöglichen und abzurechnen (Nutzungsdaten), werden ausschließlich zur Abwicklung der zwischen uns abgeschlossenen Kaufverträge verwendet. Solche Nutzungsdaten sind insbesondere die Merkmale zu Ihrer Identifikation als Nutzer, Angaben über Beginn und Ende sowie über den Umfang der jeweiligen Nutzung und Angaben über die von Ihnen als Nutzer in Anspruch genommenen Telemedien.
 
Sämtliche von Ihnen mitgeteilten personenbezogenen Daten werden wir ausschließlich gemäß den Bestimmungen des deutschen Datenschutzrechts erheben, verarbeiten und speichern. 

Ihre personenbezogenen Daten, soweit diese für die Begründung, inhaltliche Ausgestaltung oder Änderung des Vertragsverhältnisses erforderlich sind (Bestandsdaten), werden ausschließlich zur Abwicklung der zwischen uns abgeschlossenen Kaufverträge verwendet, etwa zur Zustellung von Waren an die von Ihnen angegebene Adresse. Eine darüber hinausgehende Nutzung Ihrer Bestandsdaten für Zwecke der Werbung, der Marktforschung oder zur bedarfsgerechten Gestaltung unserer Angebote erfolgt nicht.

**Comment by Macho2406** [comment]
Widerrufsrecht
 
Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.
 
Die Widerrufsfrist beträgt vierzehn Tage ab dem Tag an dem Sie oder ein von Ihnen benannter Dritter, der nicht der Beförderer ist, die letzte Ware in Besitz genommen haben bzw. hat.
 
Um Ihr Widerrufsrecht auszuüben, müssen Sie uns (Esotech) mittels einer eindeutigen Erklärung (z.B. ein mit der Post versandter Brief, Telefax oder E-Mail) über Ihren Entschluss, diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.
 
Zur Wahrung der Widerrufsfrist reicht es aus, dass Sie die Mitteilung über die Ausübung des Widerrufsrechts vor Ablauf der Widerrufsfrist absenden.


Folgen des Widerrufs
 
Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrages bei uns eingegangen ist. Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben, es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet. Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben, dass Sie die Waren wieder zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist.
 
Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen vierzehn Tagen ab dem Tag, an dem Sie uns über den Widerruf dieses Vertrages unterrichten, an uns zurückzusenden oder zu übergeben. Die Frist ist gewahrt, wenn Sie die Waren vor Ablauf der Frist von vierzehn Tagen absenden. Sie tragen die unmittelbaren Kosten der Rücksendung der Waren. Sie müssen für einen etwaigen Wertverlust der Waren nur aufkommen, wenn dieser Wertverlust auf einen zur Prüfung der Beschaffenheit, Eigenschaften und Funktionsweise der Waren nicht notwendigen Umgang mit ihnen zurückzuführen ist.
 
 
Ausschluss des Widerrufsrechtes

Das Widerrufsrecht besteht nicht bei Veträgen
 
zur Lieferung von Waren, die nicht vorgefertigt sind und für deren Herstellung eine individuelle Auswahl oder Bestimmung durch den Verbraucher maßgeblich ist oder die eindeutig auf die persönlichen Bedürfnisse des Verbrauchers zugeschnitten sind,
zur Lieferung von Waren, die schnell verderben können oder deren Verfallsdatum schnell überschritten würde,
zur Lieferung versiegelter Waren, die aus Gründen des Gesundheitsschutzes oder der Hygiene nicht zur Rückgabe geeignet sind, wenn ihre Versiegelung nach der Lieferung entfernt wurde,
zur Lieferung von Waren, wenn diese nach der Lieferung auf Grund ihrer Beschaffenheit untrennbar mit anderen Gütern vermischt wurden,
zur Lieferung alkoholischer Getränke, deren Preis bei Vertragsschluss vereinbart wurde, die aber frühestens 30 Tage nach Vertragsschluss geliefert werden können und deren aktueller Wert von Schwankungen auf dem Markt abhängt, auf die der Unternehmer keinen Einfluss hat,
zur Lieferung von Ton- oder Videoaufnahmen oder Computersoftware in einer versiegelten Packung, wenn die Versiegelung nach der Lieferung entfernt wurde,
zur Lieferung von Zeitungen, Zeitschriften oder Illustrierten mit Ausnahme von Abonnement-Verträgen.
 
Muster-Widerrufsformular
 
Wenn Sie den Vertrag wirderrufen wollen, dann füllen Sie bitte dieses Formular aus oder Sie erstellen sich unter diesen Gesichtspunkten ein eigenes Formular und senden es zurück an:
 
Esotech Informationen 
-------------------------------------------------------------------------------------------------------------------------------------------------
 
Hiermit widerrufe(n) ich / wir (*) den von mir / uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren / die Erbringung folgenden Dienstleistung (*)
 
Bestellt am (*) / erhalten am (*)
 
Name des / der Verbraucher(s)
 
Anschirft des / der Verbraucher(s)
 
Unterschrift des / der Verbraucher(s) (nur bei Mitteilung auf Papier)
 
Datum
 
(*) Unzutreffendes bitte streichen

**Comment by Macho2406** [comment]
AGB

http://www.agb.de/

**Comment by Nanabell** [comment]
- [ ] Rechtlichen Hinweise
- [ ] Datenschutz
- [ ] Widerrufsrecht

**Comment by Macho2406** [comment]
Allgemeine Geschäftsbedingungen der Firma Esotech<br />

<br />
<p style="font-weight: bold; padding-bottom: 10px;">§1 Geltung gegenüber Unternehmern und Begriffsdefinitionen</p>
(1) Die nachfolgenden Allgemeinen Geschäftbedingungen gelten für alle Lieferungen zwischen uns und einem Verbraucher
in ihrer zum Zeitpunkt der Bestellung gültigen Fassung.<br />
<br />
Verbraucher ist jede natürliche Person, die ein Rechtsgeschäft zu Zwecken abschließt, die überwiegend weder
ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden können (§ 13 BGB).
<br />

    <br />
<p style="font-weight: bold; padding-bottom: 10px;">§2 Zustandekommen eines Vertrages, Speicherung des Vertragstextes</p>
(1) Die folgenden Regelungen über den Vertragsabschluss gelten für Bestellungen über unseren Internetshop http://esotech.jit4u.de/shop/ .<br />
<br />
<b>(2) Im Falle des Vertragsschlusses kommt der Vertrag mit<br />

<div style="font-weight: bold; margin-left: 20px;" >
<br />
Esotech<br />
Torsten Jahn<br />
Jahnstraße 43<br />
D-36119 Neuhof<br />
Registernummer <br />
Registergericht Neuhof<br />
<br />
</div>
zustande.<br /></b>
<br />
(3) Die Präsentation der Waren in unserem Internetshop stellen kein rechtlich bindendes Vertragsangebot unsererseits dar,
sondern sind nur eine unverbindliche Aufforderungen an den Verbraucher, Waren zu bestellen. Mit der Bestellung der gewünschten Ware gibt der Verbraucher ein für
ihn verbindliches Angebot auf Abschluss eines Kaufvertrages ab.<br />
(4) Bei Eingang einer Bestellung in unserem Internetshop gelten folgende Regelungen:
Der Verbraucher gibt ein bindendes Vertragsangebot ab, indem er die in unserem Internetshop vorgesehene Bestellprozedur erfolgreich durchläuft.<br />
<br />
Die Bestellung erfolgt in folgenden Schritten:<br />
<br />
<div class="ml20">
     
    1) Auswahl der gewünschten Ware in den Warenkorb<br /> 
     
    2) Bestätigen durch Anklicken der Buttons „Zur Kasse gehen"<br /> 
     
    3) Prüfung der Angaben im Warenkorb durch die Übersicht<br /> 
     
    4) Anmeldung im Internetshop nach Registrierung und Eingabe der Anmelderangaben (E-Mail-Adresse und Passwort)<br /> 
     
    5) Angabe der Lieferadresse<br /> 
     
    6) Auswahl des Versandienstes<br /> 
     
    7) AGB's bestätigen<br /> 
     
    8) Zahlungsart auswählen<br /> 
     
    9) Übersicht über die Bestellung und abschließender Button zum Bestellen<br /> 
     
<br />
</div>
Der Verbraucher kann vor dem verbindlichen Absenden der Bestellung durch Betätigen der in dem von ihm verwendeten Internet-Browser enthaltenen „Zurück“-Taste nach
Kontrolle seiner Angaben wieder zu der Internetseite gelangen, auf der die Angaben des Kunden erfasst werden und Eingabefehler berichtigen bzw. durch Schließen des
Internetbrowsers den Bestellvorgang abbrechen.
Wir bestätigen den Eingang der Bestellung unmittelbar durch eine automatisch generierte E-Mail („Auftragsbestätigung“). Mit dieser nehmen wir Ihr Angebot an.
<br />
<br />
(5) Speicherung des Vertragstextes bei Bestellungen über unseren Internetshop : Wir senden Ihnen die Bestelldaten und unsere AGB per
E-Mail zu. Die AGB können Sie jederzeit auch unter http://esotech.jit4u.de/shop/content/3-allgemeine-geschaeftsbedingungen  einsehen.

Ihre Bestelldaten sind aus Sicherheitsgründen nicht mehr über das Internet zugänglich.
<br />


    <br />
<p style="font-weight: bold; padding-bottom: 10px;">§3 Preise, Versandkosten, Zahlung, Fälligkeit</p>
(1) Die angegebenen Preise enthalten die gesetzliche Umsatzsteuer und sonstige Preisbestandteile. Hinzu kommen etwaige Versandkosten.<br />
<br />
(2) Der Verbraucher hat die Möglichkeit der Zahlung per 
            PayPal, 
     
        
     
        
     Kreditkarte(
                Visa, 
                Mastercard 
         )
     
        
     
        
.<br />
<br />
 

<br />
<p style="font-weight: bold; padding-bottom: 10px;">§4 Lieferung</p>
(1) Sofern wir dies in der Produktbeschreibung nicht deutlich anders angegeben haben, sind alle von uns angebotenen Artikel sofort versandfertig.
Die Lieferung erfolgt hier spätesten innerhalb von 5 Werktagen.
Dabei beginnt die Frist für die Lieferung im Falle der Zahlung per Vorkasse am Tag nach
Zahlungsauftrag an die mit der Überweisung beauftragte Bank und bei allen anderen Zahlungsarten am Tag nach Vertragsschluss zu laufen.
Fällt das Fristende auf einen Samstag, Sonntag oder gesetzlichen Feiertag am Lieferort, so endet die Frist am nächsten Werktag.
<br /><br />

(2) Die Gefahr des zufälligen Untergangs und der zufälligen Verschlechterung der
verkauften Sache geht auch beim Versendungskauf erst mit der Übergabe der Sache an den Käufer auf diesen über.  <br />


<br />
<p style="font-weight: bold; padding-bottom: 10px;">§5 Eigentumsvorbehalt</p>
Wir behalten uns das Eigentum an der Ware bis zur vollständigen Bezahlung des Kaufpreises vor. <br />



            <br />

****************************************************************************************************
<br />
<p style="font-weight: bold; padding-bottom: 10px;">§6 Widerrufsrecht des Kunden als Verbraucher:
</p>

<b>
    Widerrufsrecht für Verbraucher</b><br />
    <br />
    Verbrauchern steht ein Widerrufsrecht nach folgender Maßgabe zu, wobei Verbraucher jede natürliche Person ist, die ein Rechtsgeschäft zu Zwecken abschließt,
    die überwiegend weder ihrer gewerblichen noch ihrer selbständigen beruflichen Tätigkeit zugerechnet werden können:

    <br />
    <br />

    <p style="font-weight: bold; padding-bottom: 1px; text-align: center;">Widerrufsbelehrung</p>
    <br />
    <b>Widerrufsrecht</b><br />
    <br />
    Sie haben das Recht, binnen vierzehn Tagen ohne Angabe von Gründen diesen Vertrag zu widerrufen.
    <br />
    <br />
    Die Widerrufsfrist beträgt vierzehn Tage, ab dem Tag, an dem Sie oder ein von Ihnen benannter Dritter,
        der nicht der Beförderer ist, die Waren in Besitz genommen haben bzw. hat.

    <br /><br />
    Um Ihr Widerrufsrecht auszuüben, müssen Sie uns<br />
    <div style="margin-left:20px; margin-top: 5px; margin-bottom:5px;">
        Esotech<br />
        Torsten Jahn<br />
        Jahnstraße 43<br />
        D-36119 Neuhof<br />
        E-Mail krull.niklas@web.de<br />
            </div>
    mittels einer eindeutigen Erklärung (z.B. ein mit der Post versandter Brief, Telefax oder E-Mail) über Ihren Entschluss,
    diesen Vertrag zu widerrufen, informieren. Sie können dafür das beigefügte Muster-Widerrufsformular verwenden, das jedoch nicht vorgeschrieben ist.
    <br />
    <br />

    <b>Widerrufsfolgen</b>
    <br /><br />
    Wenn Sie diesen Vertrag widerrufen, haben wir Ihnen alle Zahlungen, die wir von Ihnen erhalten haben, einschließlich der
    Lieferkosten (mit Ausnahme der zusätzlichen Kosten, die sich daraus ergeben, dass Sie eine andere Art der Lieferung als
    die von uns angebotene, günstigste Standardlieferung gewählt haben), unverzüglich und spätestens binnen vierzehn Tagen
    ab dem Tag zurückzuzahlen, an dem die Mitteilung über Ihren Widerruf dieses Vertrags bei uns eingegangen ist.
    Für diese Rückzahlung verwenden wir dasselbe Zahlungsmittel, das Sie bei der ursprünglichen Transaktion eingesetzt haben,
    es sei denn, mit Ihnen wurde ausdrücklich etwas anderes vereinbart; in keinem Fall werden Ihnen wegen dieser Rückzahlung Entgelte berechnet.
<br />
<br />

    Wir können die Rückzahlung verweigern, bis wir die Waren wieder zurückerhalten haben oder bis Sie den Nachweis erbracht haben,
    dass Sie die Waren zurückgesandt haben, je nachdem, welches der frühere Zeitpunkt ist.
<br />
<br />

    Sie haben die Waren unverzüglich und in jedem Fall spätestens binnen vierzehn Tagen ab dem Tag, an dem Sie uns über den
    Widerruf dieses Vertrages unterrichten, an uns zurückzusenden oder zu übergeben. Die Frist ist gewahrt,
    wenn Sie die Waren vor Ablauf der Frist von vierzehn Tagen absenden.
    <br />
    <br />

Sie tragen die unmittelbaren Kosten der Rücksendung der Waren.<br />
<br />

    
    <b>Ende der Widerrufsbelehrung</b>
<br />
<br />
****************************************************************************************************

<br />
    




<p style="font-weight: bold; padding-bottom: 10px;">§7 Widerrufsformular</p>

<p style="text-align: center; font-weight: bold;">Muster-Widerrufsformular</p>
(Wenn Sie den Vertrag widerrufen wollen, dann füllen Sie bitte dieses Formular aus und senden Sie es zurück.)<br />
<div style="border: 1px solid #000000;padding: 10px;">
An :<br />
Esotech<br />
Torsten Jahn<br />
Jahnstraße 43<br />
D-36119 Neuhof<br />
E-Mail krull.niklas@web.de<br />
<br />

Hiermit widerrufe(n) ich/wir (*) den von mir/uns (*) abgeschlossenen Vertrag über den Kauf der folgenden Waren (*)/die Erbringung der folgenden Dienstleistung (*)<br />
<br />
_____________________________________________________<br />
<br />
Bestellt am (*)/erhalten am (*)<br />
<br />
__________________<br />
<br />
Name des/der Verbraucher(s)<br />
<br />
_____________________________________________________<br />
<br />
Anschrift des/der Verbraucher(s)<br />
<br />
<br />
_____________________________________________________<br />
<br />
Unterschrift des/der Verbraucher(s) (nur bei Mitteilung auf Papier)<br />
<br />
__________________<br />
<br />
Datum<br />
<br />
__________________<br />
<br />
</div>
(*) Unzutreffendes streichen.<br />



<br />
<p style="font-weight: bold; padding-bottom: 10px;">§8 Gewährleistung
</p>

Es gelten die gesetzlichen Gewährleistungsregelungen.
<br />


<br />
<p style="font-weight: bold; padding-bottom: 10px;">§9 Vertragssprache</p>
 Als Vertragssprache steht ausschließlich Deutsch zur Verfügung.<br />

<br />
<br />
<p>Stand der AGB Mär.2017</p>

<p><i><a href="http://www.agb.de">Gratis AGB</a> erstellt von agb.de</i></p>

**Comment by Macho2406** [comment]
https://hastebin.com/eninadagom.xml
