### ISSUE TITLE
Rechtliches - Dürfen Schüler Geld verdienen ?

### ISSUE THREAD

**Issue by Nanabell** [Nanabell/Esoteric-Website#2]
Dürfen Schüler überhaupt Geld einnehmen ?

**Comment by Dustin2112** [comment]
"_Also alles was über deinen shop verkauft wird, MUSS versteuert werden. 
 - sonst ist das Schwarzarbeit

es gibt von Bundesland zu Bundesland unterschiedliche Steuerbeiträge am besten gehst du zu deiner IHK vor Ort die helfen dir auf jeden Fall weiter_"
~kiwie

**Comment by Dustin2112** [comment]
**Eskalation**
Durch Recherche im rechtlichen Bereich ist uns klar geworden, dass wir nicht ohne weiters einen Online-Shop eröffnen und dort eigene Artikel verkaufen können. Dabei müssten wir zunächst ein eigenes Unternehmen eröffnen und anschließend Steuern und andere Abgaben mit einrechnen, welche wir mit der IHK abklären müssten. 

**Deeskalation**
Da dies eindeutig den Rahmen des Projekts sprengt, haben sich die Gruppenmitglieder zusammen mit Herr Jahn darauf geeinigt, einen Shop anzulegen, dort jedoch eine Aufklärung, statt einer Verkaufsoption, einzublenden.
