### ISSUE TITLE
Shop

### ISSUE THREAD

**Issue by Nanabell** [Nanabell/Esoteric-Website#21]
Funktionsfähiger Shop

**Comment by Dustin2112** [comment]
Keine Verkäufe da #2 
Dennoch Artikel anbieten

**Comment by Nanabell** [comment]
PrestaShop auf Server installiert zugangsdaten sind gespeichert

**Comment by Nanabell** [comment]
Shop ist funktionsfähig muss jedoch noch angepasst werden

**Comment by Dustin2112** [comment]
Mehrfach überarbeitet und Artikel und mehr eingefügt. Kategorien überarbeitet und Artikel zugeordnet, nun sozusagen "fertig"
