### ISSUE TITLE
Artikelbilder

### ISSUE THREAD

**Issue by Nanabell** [Nanabell/Esoteric-Website#29]
Artikelbilder für die Produkte erstellen und auf die Website Hochladen

**Comment by Dustin2112** [comment]
Pics taken and saved//uploaded

**Comment by Nanabell** [comment]
21 März => Dustin & Christopher haben professionelle Bilder aufgenommen und hochgeladen

**Comment by Nanabell** [comment]
https://drive.google.com/drive/folders/0Bz-r1FZesdTaNXZKcGNWaDV1NGc
