### ISSUE TITLE
Artikelbeschreibung

### ISSUE THREAD

**Issue by Nanabell** [Nanabell/Esoteric-Website#30]
Artikelbeschreibung für Produkte erstellen und auf die Website für die Produkte eintragen

**Comment by Macho2406** [comment]
Rechtliche Hinweise: Wir möchten Sie darauf aufmerksam machen, dass bei den Produkten, die wir auf unserer Homepage (www.esotech.jit4u.de) und in sonstigen Produktinformationen anbieten, nach den naturwissenschaftlichen Kriterien der Schulwissenschaft keine Wirksamkeit besteht. Nach den Theorien und Standards der Schulwissenschaft ist es ausgeschlossen, dass unsere Geräte Orgonenergie sammeln und konzentrieren. 

Als Käufer der Esotech Produkte erwerben Sie also Geräte, die auf Gedanken von Außenseitern beruhen. Nach den naturwissenschaftlichen Kriterien der Schulwissenschaft können die Produkte lediglich eine Placebo-Wirkung auf Gesundheit und Wohlbefinden der Anwender haben.

Bei einem Krankheitsverdacht, gesundheitlichen Beschwerden oder Erkrankungen wenden Sie sich zur Diagnose und Behandlung bitte unbedingt und unverzüglich an Ihren Arzt oder Heilpraktiker.
 
Die Anwendung der Esotech Produkte dient Ihrem Wohlbefinden und hat keine medizinischen Zwecke. Ihre Nutzung sollte nicht dazu führen, dass Sie eine Untersuchung oder die Betreuung durch Ihren Arzt oder Heilpraktiker hinauszögern, unterbrechen oder beenden.

Alle Angaben zu orgonspezifischen Eigenschaften der Esotech Produkte auf unserer Homepage (www.esotech.jit4u.de) und in sonstigen Produktinformationen von uns beruhen auf praktischen Erfahrungen im Umgang mit diesen Produkten. Durch technische Messgeräte sind sie so nicht festzustellen.

**Comment by Nanabell** [comment]
21, 28 März => Julian & Niklas Haben für einge Produkte bescheibungen erstellt.

**Comment by Nanabell** [comment]
18 April => Dustin hat die Beschreibungen überarbeitet

**Comment by Dustin2112** [comment]
Artikelbeschreibungen 24. April wurde von Team überarbeitet
