### ISSUE TITLE
Webseiten Technik - CMS (Drupal, WordPress, Joomla, Typo3)

### ISSUE THREAD

**Issue by Nanabell** [Nanabell/Esoteric-Website#7]
Welche Software werden wir für die Umsetzung benutzen?

**Comment by Macho2406** [comment]
Wir nehmen WordPress.

**Comment by Dustin2112** [comment]
-Note: Squarespace=?

**Comment by Nanabell** [comment]
Squarespace ist nicht verwendbar

**Comment by Nanabell** [comment]
Wurde durch #16 geschlossen
